sudo: false
language: java
jdk:
  - openjdk8
install: true
script:
  - mvn verify -B
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings etc/deploy-settings.xml"
  - mvn verify coveralls:report -Prun-coverage
cache:
  directories:
    - '$HOME/.m2/repository'
